version: '3.8'

networks:
  bank-network:
    driver: bridge

volumes:
  postgres_data:

services:
  # Infrastructure Services
  postgres:
    image: postgres:15-alpine
    container_name: bank-postgres
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bank-network
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --import-realm
    volumes:
      - ./keycloak-data:/opt/keycloak/data
      - ./keycloak-realm:/opt/keycloak/data/import
    networks:
      - bank-network
    restart: unless-stopped

  # Core Services
  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      JAVA_OPTS: "-Xmx512m -Xms256m"
    networks:
      - bank-network
    restart: unless-stopped

  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      JAVA_OPTS: "-Xmx512m -Xms256m"
    networks:
      - bank-network
    depends_on:
      - config-server
    restart: unless-stopped

  # API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "9001:9001"
    environment:
      JAVA_OPTS: "-Xmx512m -Xms256m"
      CONFIG_SERVER_URL: "http://config-server:8888"
      EUREKA_SERVER_URL: "http://eureka-server:8761/eureka"
    networks:
      - bank-network
    depends_on:
      - config-server
      - eureka-server
    restart: unless-stopped

  # Business Services
  accounts-service:
    build:
      context: .
      dockerfile: accounts-service/Dockerfile
    container_name: accounts-service
    ports:
      - "8091:8091"
    environment:
      JAVA_OPTS: "-Xmx512m -Xms256m"
      SPRING_PROFILES_ACTIVE: "postgres"
      CONFIG_SERVER_URL: "http://config-server:8888"
      EUREKA_SERVER_URL: "http://eureka-server:8761/eureka"
      DATABASE_URL: "jdbc:postgresql://postgres:5432/bank"
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "1"
    networks:
      - bank-network
    depends_on:
      - config-server
      - eureka-server
      - postgres
      - keycloak
    restart: unless-stopped

  cash-service:
    build:
      context: .
      dockerfile: cash-service/Dockerfile
    container_name: cash-service
    ports:
      - "8092:8092"
    environment:
      JAVA_OPTS: "-Xmx512m -Xms256m"
      CONFIG_SERVER_URL: "http://config-server:8888"
      EUREKA_SERVER_URL: "http://eureka-server:8761/eureka"
    networks:
      - bank-network
    depends_on:
      - config-server
      - eureka-server
    restart: unless-stopped

  exchange-service:
    build:
      context: .
      dockerfile: exchange-service/Dockerfile
    container_name: exchange-service
    ports:
      - "8093:8093"
    environment:
      JAVA_OPTS: "-Xmx512m -Xms256m"
      CONFIG_SERVER_URL: "http://config-server:8888"
      EUREKA_SERVER_URL: "http://eureka-server:8761/eureka"
    networks:
      - bank-network
    depends_on:
      - config-server
      - eureka-server
      - keycloak
    restart: unless-stopped

  transfer-service:
    build:
      context: .
      dockerfile: transfer-service/Dockerfile
    container_name: transfer-service
    ports:
      - "8094:8094"
    environment:
      JAVA_OPTS: "-Xmx512m -Xms256m"
      CONFIG_SERVER_URL: "http://config-server:8888"
      EUREKA_SERVER_URL: "http://eureka-server:8761/eureka"
    networks:
      - bank-network
    depends_on:
      - config-server
      - eureka-server
    restart: unless-stopped

  blocker-service:
    build:
      context: .
      dockerfile: blocker-service/Dockerfile
    container_name: blocker-service
    ports:
      - "8095:8095"
    environment:
      JAVA_OPTS: "-Xmx512m -Xms256m"
      CONFIG_SERVER_URL: "http://config-server:8888"
      EUREKA_SERVER_URL: "http://eureka-server:8761/eureka"
    networks:
      - bank-network
    depends_on:
      - config-server
      - eureka-server
    restart: unless-stopped

  notifications-service:
    build:
      context: .
      dockerfile: notifications-service/Dockerfile
    container_name: notifications-service
    ports:
      - "8096:8096"
    environment:
      JAVA_OPTS: "-Xmx512m -Xms256m"
      CONFIG_SERVER_URL: "http://config-server:8888"
      EUREKA_SERVER_URL: "http://eureka-server:8761/eureka"
    networks:
      - bank-network
    depends_on:
      - config-server
      - eureka-server
    restart: unless-stopped

  exchange-generator-service:
    build:
      context: .
      dockerfile: exchange-generator-service/Dockerfile
    container_name: exchange-generator-service
    ports:
      - "8097:8097"
    environment:
      JAVA_OPTS: "-Xmx512m -Xms256m"
      CONFIG_SERVER_URL: "http://config-server:8888"
      EUREKA_SERVER_URL: "http://eureka-server:8761/eureka"
    networks:
      - bank-network
    depends_on:
      - config-server
      - eureka-server
      - exchange-service
    restart: unless-stopped

  # Frontend
  front-ui:
    build:
      context: .
      dockerfile: front-ui/Dockerfile
    container_name: front-ui
    ports:
      - "8090:8090"
    environment:
      JAVA_OPTS: "-Xmx512m -Xms256m"
      CONFIG_SERVER_URL: "http://config-server:8888"
      EUREKA_SERVER_URL: "http://eureka-server:8761/eureka"
    networks:
      - bank-network
    depends_on:
      - config-server
      - eureka-server
      - api-gateway
      - accounts-service
    restart: unless-stopped 