server:
  port: 9001
spring:
  application:
    name: api-gateway
  config:
    import: "configserver:http://localhost:8888"

#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.cloud.gateway: DEBUG
#    org.springframework.security.oauth2: DEBUG
#    org.springframework.web.reactive: DEBUG
#    reactor.netty: DEBUG