server:
  port: 8090
spring:
  application:
    name: front-ui
  config:
    import: "configserver:http://${CONFIG_SERVER_PATH:localhost}:8888"
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.cloud.gateway: DEBUG
#    org.springframework.security.oauth2: DEBUG
#    org.springframework.web.reactive: DEBUG
#    reactor.netty: DEBUG