server:
  port: 8092
spring:
  application:
    name: blocker-service
  config:
    import: "optional:configserver:http://${CONFIG_SERVER_PATH:localhost}:8888"

logging:
  level:
    org.springframework.security: DEBUG