spring:
  application:
    name: eureka-server
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${HOST}:8761/eureka/
    # Explicitly disable TLS to prevent binding issues
    tls:
      enabled: false
  server:
    enable-self-preservation: false
  instance:
    hostname: ${HOST}
    prefer-ip-address: false