spring:
  cloud:
    gateway:
      server:
        webmvc:
          discovery:
            locator:
              enabled: true
              lowerCaseServiceId: true
          routes:
            - id: accounts-service
              uri: lb://accounts-service      # адрес user сервиса
              predicates:
                - Path=/api/hello          # перехватываем путь /api/hello
              filters:
                - TokenRelay=gateway-client # use clientRegistrationId
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/bankrealm/protocol/openid-connect/token
        registration:
          gateway-client: # clientRegistrationId
            provider: keycloak
            client-id: gateway
            client-secret: 64bHVrtzGzfuhd0CWZA7sldmpDQ95d6u
            scope: resource.read
            authorization-grant-type: client_credentials

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
