spring:
  cloud:
    gateway:
      routes:
        # Accounts Service
        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/api/hello, /api/auth/**
          metadata:
            service-name: accounts-service

        - id: blocker-service
          uri: lb://blocker-service
          predicates:
            - Path=/api/users/**, /users/**
          metadata:
            service-name: blocker-service

        - id: cash-service
          uri: lb://cash-service
          predicates:
            - Path=/api/transactions/**, /transactions/**
          metadata:
            service-name: cash-service
            
        # Notifications Service (example - adjust URI as needed)
        - id: exchange-generator-service
          uri: lb://exchange-generator-service
          predicates:
            - Path=/api/notifications/**, /notifications/**
          metadata:
            service-name: exchange-generator-service
            
        # General API route for backward compatibility
#        - id: general-api
#          uri: http://localhost:8091
#          predicates:
#            - Path=/api/**
#          metadata:
#            service-name: general-api

        - id: exchange-service
          uri: lb://exchange-service
          predicates:
            - Path=/exchange/course/update, /exchange/course
          metadata:
            service-name: exchange-service

        - id: notifications-service
          uri: lb://notifications-service
          predicates:
            - Path=/api/notifications/**, /notifications/**
          metadata:
            service-name: notifications-service

        - id: transfer-service
          uri: lb://transfer-service
          predicates:
            - Path=/api/notifications/**, /notifications/**
          metadata:
            service-name: transfer-service

#      discovery:
#        locator:
#          enabled: true
#          lowerCaseServiceId: true
#      routes:
#        - id: accounts-service
#          uri: lb://accounts-service      # адрес user сервиса
#          predicates:
#            - Path=/api/hello          # перехватываем путь /api/hello
#          filters:
#            - TokenRelay=gateway-client # use clientRegistrationId
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/bankrealm/protocol/openid-connect/token
            authorization-uri: http://localhost:8080/realms/bankrealm/protocol/openid-connect/auth
            user-info-uri: http://localhost:8080/realms/bankrealm/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8080/realms/bankrealm/protocol/openid-connect/certs
            issuer-uri: http://localhost:8080/realms/bankrealm
        registration:
          gateway-client:
            provider: keycloak
            client-id: gateway
            client-secret: DOh7wYosZk3mneOFOm2NGefWk5IzbVyi
            scope: resource.read
            authorization-grant-type: client_credentials
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bankrealm

## Gateway authentication configuration
#gateway:
#  auth:
#    # Service path mappings to OAuth2 client registration IDs
#    service-client-mappings:
#      "/api/accounts/": "gateway-client"
#      "/accounts/": "gateway-client"
#      "/api/users/": "gateway-client"
#      "/users/": "gateway-client"
#      "/api/transactions/": "gateway-client"
#      "/transactions/": "gateway-client"
#      "/api/notifications/": "gateway-client"
#      "/notifications/": "gateway-client"
#      # You can add different clients for different services
#      # "/api/admin/": "admin-gateway-client"
#      # "/api/internal/": "internal-gateway-client"
#
#    # Paths that should skip authentication entirely
#    skip-auth-paths:
#      - "/auth/"
#      - "/public/"
#      - "/actuator/"
#      - "/health"
#      - "/info"
#      - "/swagger-ui/"
#      - "/v3/api-docs/"
#
#    # Default OAuth2 client registration ID for API paths without specific mapping
#    default-client-registration-id: "gateway-client"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
