server:
  port: 8888 # Порт, на котором будет запущен Config Server
spring:
  application:
    name: config-server
  profiles:
    active: native # Профиль native необходимо включать для поддержки хранилища в локальной файловой системе
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo/ # Фолдер, из которого загружаются конфигурации
#eureka: # нет смысла регистрировать конфиг в eureka, так как он нужен на стадии запуска сервисов
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true
#    fetch-registry: true